parser: "@typescript-eslint/parser"
parserOptions:
  project: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended-type-checked"
plugins:
  - "@typescript-eslint"
ignorePatterns:
  - dist
  - ".eslintrc.*"
root: true
